services:
  api:
    build: .
    container_name: gosheild-api
    ports:
      - "8080:8080"
    environment:
      - RATE_LIMIT=100
      - WINDOW_SECONDS=60
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: gosheild-redis
    ports:
      - "6380:6379"
